-- respira_gold.station_overrides — operator decisions written by the Django
-- backoffice (respira-webapp) and read by int_station_status_overrides.
--
-- This pipeline is the table's DDL owner: respira-data provisions every
-- relation it depends on at runtime, so warehouse_bootstrap can establish the
-- table before the backend is deployed. respira-webapp keeps a matching Django
-- model and owns every application-level write (see api/models.py
-- StationOverride, migration 0005_stationoverride).
--
-- The definition below must stay byte-for-byte compatible with what Django's
-- schema editor emits for that model. It was derived from
-- `manage.py sqlmigrate api 0005_stationoverride` against PostgreSQL, not
-- written by hand, because Django will not reconcile a table whose columns,
-- nullability, constraint names or index names differ from its own state:
--
--   CREATE TABLE "station_overrides" ("id" bigint NOT NULL PRIMARY KEY
--     GENERATED BY DEFAULT AS IDENTITY, "station_code" varchar(255) NOT NULL,
--     "field" varchar(255) NOT NULL, "value" varchar(255) NOT NULL,
--     "note" text NOT NULL, "change_date" timestamp with time zone NOT NULL,
--     "processed" boolean NOT NULL);
--   ALTER TABLE "station_overrides" ADD CONSTRAINT
--     "uniq_station_override_code_field" UNIQUE ("station_code", "field");
--   CREATE INDEX "station_overrides_station_code_82e10f45" ...
--   CREATE INDEX "station_overrides_station_code_82e10f45_like" ...
--
-- Two details of that output are easy to get wrong by hand:
--
-- * `id` is an IDENTITY column, not `bigserial`. Django 4.2 emits
--   `GENERATED BY DEFAULT AS IDENTITY`, which owns its sequence internally —
--   there is no `station_overrides_id_seq` to grant on, and INSERT on the table
--   is sufficient for the backend to write rows.
-- * The `_like` index (varchar_pattern_ops) is created by `db_index=True` on a
--   varchar column so LIKE queries can use it. Django's state expects both
--   indexes, so both are created here.
--
-- Defaults live in the Django model rather than the database
-- (`change_date=timezone.now`, `processed=False`, `note` blank), which is why
-- the columns below carry NOT NULL without a DDL default: that is exactly what
-- Django emits, and adding database defaults here would diverge from its state.
-- Every statement is idempotent and fully qualified.

create table if not exists respira_gold.station_overrides (
    id bigint not null primary key generated by default as identity,
    station_code varchar(255) not null,
    field varchar(255) not null,
    value varchar(255) not null,
    note text not null,
    change_date timestamptz not null,
    processed boolean not null
);

-- Idempotent equivalent of Django's ADD CONSTRAINT: ALTER TABLE ... ADD
-- CONSTRAINT has no IF NOT EXISTS in PostgreSQL, so the catalog is checked
-- first. The name must match the model's Meta.constraints entry.
do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'uniq_station_override_code_field'
          and conrelid = 'respira_gold.station_overrides'::regclass
    ) then
        alter table respira_gold.station_overrides
            add constraint uniq_station_override_code_field
            unique (station_code, field);
    end if;
end
$$;

create index if not exists station_overrides_station_code_82e10f45
    on respira_gold.station_overrides (station_code);

create index if not exists station_overrides_station_code_82e10f45_like
    on respira_gold.station_overrides (station_code varchar_pattern_ops);

comment on table respira_gold.station_overrides is
'Operator overrides of station fields, written by the respira-webapp Django backoffice and read by int_station_status_overrides. Provisioned here; never written by dbt.';
comment on column respira_gold.station_overrides.station_code is
'dim_stations.code the override applies to; the pipeline''s stable natural key.';
comment on column respira_gold.station_overrides.field is
'Name of the stations column being overridden. Only is_station_on is consumed today.';
comment on column respira_gold.station_overrides.value is
'Target value for field. For is_station_on: inactive holds the station off, active records that the hold was lifted.';
comment on column respira_gold.station_overrides.note is
'Operator''s reason for the override. Required by the admin workflow.';
comment on column respira_gold.station_overrides.change_date is
'When the override was last recorded.';
comment on column respira_gold.station_overrides.processed is
'Reserved and unused: nothing writes it and dbt never reads it. An override is a desired state, not an event, so it must keep applying on every run; filtering on this flag would let a held-off station turn itself back on after the first run.';

-- The backend role operates the table but never creates it: it gets CRUD and
-- schema USAGE, never CREATE on the schema. That split is the point of
-- provisioning here — it is what the failed deployment lacked.
--
-- The role name is not hardcoded: BACKEND_DB_ROLE is passed in by
-- ensure_station_overrides_table(). Granting is skipped when the role does not
-- exist so a local or CI database without the backend role still bootstraps.
do $$
begin
    if exists (select 1 from pg_roles where rolname = '{backend_role}') then
        grant usage on schema respira_gold to {backend_role};
        grant select, insert, update, delete
            on respira_gold.station_overrides to {backend_role};
    else
        raise notice
            'Role % not found; skipping station_overrides grants.',
            '{backend_role}';
    end if;
end
$$;
