"""Contract and bootstrap tests for respira_gold.station_overrides.

The table is read by int_station_status_overrides through the respira_webapp dbt
source and written by the respira-webapp backoffice, so this pipeline provisions
it. Two properties matter enough to pin down here:

* The DDL must stay compatible with what Django's schema editor emits for the
  StationOverride model, down to constraint and index names — Django will not
  reconcile a table whose state differs from its own.
* A failure must fail the bootstrap. Logging a warning while the Prefect flow
  finishes green is the deployment gap this provisioning exists to close.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from pipelines.flows import warehouse_bootstrap as warehouse_bootstrap_flow
from pipelines.tasks import db

REPO_ROOT = Path(__file__).resolve().parents[1]


def _read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def _rendered_sql(backend_role: str = "backenduser") -> str:
    return _read("pipelines/sql/04_station_overrides_table.sql").format(
        backend_role=backend_role
    )


def test_station_overrides_sql_matches_the_django_model_contract():
    sql = _rendered_sql()

    assert "create table if not exists respira_gold.station_overrides" in sql

    # Columns, types and nullability exactly as `manage.py sqlmigrate api
    # 0005_stationoverride` emits them. `id` is an IDENTITY column, not
    # bigserial: Django 4.2 emits GENERATED BY DEFAULT AS IDENTITY, which owns
    # its sequence internally, so there is no separate sequence to grant on.
    assert "id bigint not null primary key generated by default as identity" in sql
    assert "station_code varchar(255) not null" in sql
    assert "field varchar(255) not null" in sql
    assert "value varchar(255) not null" in sql
    assert "note text not null" in sql
    assert "change_date timestamptz not null" in sql
    assert "processed boolean not null" in sql

    # Defaults live in the Django model, not the database, so the DDL must not
    # introduce database-side ones that would diverge from Django's state.
    assert "change_date timestamptz not null default" not in sql
    assert "processed boolean not null default" not in sql

    # Constraint and index names are part of the contract: Django addresses them
    # by name. The hash suffix comes from Django's own index naming.
    assert "constraint uniq_station_override_code_field" in sql
    assert "unique (station_code, field)" in sql
    assert "station_overrides_station_code_82e10f45" in sql
    assert "station_overrides_station_code_82e10f45_like" in sql
    assert "varchar_pattern_ops" in sql


def test_station_overrides_sql_is_idempotent_and_fully_qualified():
    sql = _rendered_sql()

    assert "create table if not exists" in sql
    assert sql.count("create index if not exists") == 2
    # ALTER TABLE ADD CONSTRAINT has no IF NOT EXISTS in PostgreSQL, so the
    # catalog is checked before adding it.
    assert "from pg_constraint" in sql
    assert "where conname = 'uniq_station_override_code_field'" in sql

    # Every relation is schema-qualified: the bootstrap must not depend on the
    # connection's search_path.
    assert "respira_gold.station_overrides" in sql
    assert "create table if not exists station_overrides" not in sql


def test_station_overrides_sql_grants_crud_but_never_schema_create():
    sql = _rendered_sql()

    assert "grant usage on schema respira_gold to backenduser" in sql
    assert (
        "grant select, insert, update, delete\n"
        "            on respira_gold.station_overrides to backenduser" in sql
    )

    # The whole point of provisioning here: the backend operates the table but
    # never creates it.
    assert "grant create" not in sql.lower()

    # An IDENTITY column has no separate sequence to grant on. Checked against
    # the executable SQL only — the header comment explains this, so a plain
    # substring search over the whole file would match its own rationale.
    executable = "\n".join(
        line
        for line in sql.splitlines()
        if line.strip() and not line.strip().startswith("--")
    )
    assert "station_overrides_id_seq" not in executable
    assert "grant usage, select on sequence" not in executable.lower()

    # A database without the backend role (local, CI) still bootstraps.
    assert "from pg_roles where rolname = 'backenduser'" in sql


def test_station_overrides_sql_splits_into_executable_statements(tmp_path):
    """The file's `do $$ ... $$` blocks must survive statement splitting.

    A naive split on ";" would tear their bodies apart, which is why
    ensure_station_overrides_table uses the dollar-quote-aware splitter rather
    than _render_sql_template's plain split.
    """
    sql_path = tmp_path / "rendered.sql"
    sql_path.write_text(_rendered_sql(), encoding="utf-8")

    statements = db.read_sql_statements(sql_path)

    # The splitter keeps any leading comment attached to the statement that
    # follows it, so a block is identified by containing "do $$", not by
    # starting with it.
    do_blocks = [stmt for stmt in statements if "do $$" in stmt]
    assert len(do_blocks) == 2
    for block in do_blocks:
        assert block.count("$$") == 2
        assert block.rstrip().endswith("$$")
        # The body survived intact rather than being cut at its inner ";".
        assert "end" in block

    assert any(
        "create table if not exists respira_gold.station_overrides" in stmt
        for stmt in statements
    )


def test_ensure_station_overrides_table_executes_the_rendered_statements(monkeypatch):
    captured: dict[str, object] = {}

    def _capture(engine, statements):
        captured["engine"] = engine
        captured["statements"] = statements

    monkeypatch.setattr(db, "execute_statements", _capture)

    engine = object()
    db.ensure_station_overrides_table(engine, backend_role="someotherrole")

    assert captured["engine"] is engine
    statements = captured["statements"]
    assert any("respira_gold.station_overrides" in stmt for stmt in statements)
    # The role is interpolated, not left as a placeholder.
    assert any("someotherrole" in stmt for stmt in statements)
    assert not any("{backend_role}" in stmt for stmt in statements)


def test_ensure_station_overrides_table_propagates_failures(monkeypatch):
    """A failure here must fail the bootstrap, not be logged as a warning."""
    expected_error = db.SQLAlchemyError("station_overrides DDL failed")

    def _raise(_engine, _statements):
        raise expected_error

    monkeypatch.setattr(db, "execute_statements", _raise)

    with pytest.raises(RuntimeError) as excinfo:
        db.ensure_station_overrides_table(object(), backend_role="backenduser")

    assert excinfo.value.__cause__ is expected_error
    assert "respira_gold.station_overrides" in str(excinfo.value)


@pytest.mark.parametrize(
    "bad_role",
    ["backenduser; drop table x", "back enduser", "", '"quoted"', "1role"],
)
def test_ensure_station_overrides_table_rejects_unsafe_role_names(bad_role):
    """The role is interpolated into GRANT statements, so it is validated."""
    with pytest.raises(ValueError):
        db.ensure_station_overrides_table(object(), backend_role=bad_role)


def test_warehouse_bootstrap_provisions_station_overrides(monkeypatch):
    calls: list[str] = []

    class _Engine:
        def dispose(self):
            calls.append("dispose")

    monkeypatch.setattr(
        warehouse_bootstrap_flow, "get_engine", lambda _settings: _Engine()
    )
    monkeypatch.setattr(warehouse_bootstrap_flow, "list_project_configs", lambda: [])
    monkeypatch.setattr(
        warehouse_bootstrap_flow,
        "ensure_ops_audit_tables",
        lambda _engine, **_kwargs: calls.append("ops"),
    )

    captured: dict[str, object] = {}

    def _ensure_overrides(_engine, *, backend_role):
        calls.append("station_overrides")
        captured["backend_role"] = backend_role

    monkeypatch.setattr(
        warehouse_bootstrap_flow,
        "ensure_station_overrides_table",
        _ensure_overrides,
    )

    warehouse_bootstrap_flow.warehouse_bootstrap()

    assert "station_overrides" in calls
    # Provisioned after the ops tables, and with the configured role.
    assert calls.index("ops") < calls.index("station_overrides")
    assert captured["backend_role"]


def test_warehouse_bootstrap_fails_when_station_overrides_cannot_be_provisioned(
    monkeypatch,
):
    disposed: list[bool] = []

    class _Engine:
        def dispose(self):
            disposed.append(True)

    monkeypatch.setattr(
        warehouse_bootstrap_flow, "get_engine", lambda _settings: _Engine()
    )
    monkeypatch.setattr(warehouse_bootstrap_flow, "list_project_configs", lambda: [])
    monkeypatch.setattr(
        warehouse_bootstrap_flow,
        "ensure_ops_audit_tables",
        lambda _engine, **_kwargs: None,
    )

    def _raise(_engine, **_kwargs):
        raise RuntimeError("station_overrides DDL failed")

    monkeypatch.setattr(
        warehouse_bootstrap_flow, "ensure_station_overrides_table", _raise
    )

    with pytest.raises(RuntimeError):
        warehouse_bootstrap_flow.warehouse_bootstrap()

    # The engine is still released on the failure path.
    assert disposed == [True]


def test_dbt_source_points_at_the_provisioned_relation():
    source_yml = _read("dbt/models/projects/respira_gold/sources.yml")

    assert "- name: respira_webapp" in source_yml
    assert "- name: station_overrides" in source_yml
    assert "respira_webapp_schema', 'respira_gold'" in source_yml
